# Simple Contact Form Schema
$schema: "form-schema/v1"
form:
  id: "contact-form"
  title: "Contact Form"
  version: "1.0.0"
  pages: 1

fields:
  # Name field
  - name: "name"
    type: "text"
    label: "Full Name"
    page: 1
    required: true
    maxLength: 100
    placeholder: "Enter your full name"
    position:
      x: 72
      y: 620
      width: 250
      height: 24

  # Email field
  - name: "email"
    type: "text"
    label: "Email Address"
    page: 1
    required: true
    placeholder: "your@email.com"
    validation:
      pattern: "^[\\w.-]+@[\\w.-]+\\.\\w+$"
      message: "Please enter a valid email address"
    position:
      x: 72
      y: 560
      width: 250
      height: 24

  # Phone field
  - name: "phone"
    type: "text"
    label: "Phone Number"
    page: 1
    placeholder: "(555) 123-4567"
    position:
      x: 72
      y: 500
      width: 200
      height: 24

  # Subject dropdown
  - name: "subject"
    type: "dropdown"
    label: "Subject"
    page: 1
    required: true
    options:
      - "General Inquiry"
      - "Technical Support"
      - "Sales Question"
      - "Partnership"
      - "Other"
    position:
      x: 72
      y: 440
      width: 200
      height: 24

  # Message textarea
  - name: "message"
    type: "textarea"
    label: "Your Message"
    page: 1
    required: true
    maxLength: 1000
    placeholder: "How can we help you?"
    position:
      x: 72
      y: 280
      width: 468
      height: 120

  # Newsletter checkbox
  - name: "newsletter"
    type: "checkbox"
    label: "Subscribe to our newsletter"
    page: 1
    position:
      x: 72
      y: 220
