name: 'yamlforms'
description: 'Generate fillable PDF forms with AcroForm fields from YAML schemas'
author: 'robinmordasiewicz'

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  command:
    description: 'Command to run: generate, validate'
    required: false
    default: 'generate'
  schema:
    description: 'Path to YAML schema file or glob pattern'
    required: false
    default: 'schemas/*.yaml'
  output:
    description: 'Output directory for generated files'
    required: false
    default: 'site'
  format:
    description: 'Output formats: pdf, html, docx (comma-separated)'
    required: false
    default: 'pdf'
  fail-on-error:
    description: 'Fail the action if validation errors occur'
    required: false
    default: 'true'
  publish:
    description: 'Enable GitHub Pages publishing'
    required: false
    default: 'true'
  publish-method:
    description: 'Publishing method: pages-api (requires deploy-pages action) or branch (pushes to branch directly)'
    required: false
    default: 'pages-api'
  pages-branch:
    description: 'Branch name for branch-based publishing'
    required: false
    default: 'gh-pages'
  generate-index:
    description: 'Generate index.html listing all documents'
    required: false
    default: 'true'
  index-title:
    description: 'Title for the generated index page'
    required: false
    default: 'Generated Documents'

outputs:
  files:
    description: 'JSON array of generated file paths'
  pdf-count:
    description: 'Number of PDF files generated'
  html-count:
    description: 'Number of HTML files generated'
  docx-count:
    description: 'Number of DOCX files generated'
  validation-errors:
    description: 'JSON array of validation errors (if any)'
  pages-url:
    description: 'URL of deployed GitHub Pages site'
  index-file:
    description: 'Path to generated index.html'
  pages-artifact-path:
    description: 'Path for upload-pages-artifact (use with pages-api method)'

runs:
  using: 'node20'
  main: 'dist/action/index.js'
