# Advanced Job Application Form Schema
$schema: "form-schema/v1"
form:
  id: "job-application"
  title: "Job Application"
  version: "1.0.0"
  pages: 2
  author: "HR Department"
  description: "Standard job application form"

fields:
  # ===== PAGE 1: Personal Information =====

  # Full Name
  - name: "full_name"
    type: "text"
    label: "Full Legal Name"
    page: 1
    required: true
    maxLength: 100
    placeholder: "Enter your full legal name"
    position:
      x: 72
      y: 650
      width: 300
      height: 24

  # Email
  - name: "email"
    type: "text"
    label: "Email Address"
    page: 1
    required: true
    placeholder: "your@email.com"
    validation:
      pattern: "^[\\w.-]+@[\\w.-]+\\.\\w+$"
      message: "Please enter a valid email address"
    position:
      x: 72
      y: 590
      width: 250
      height: 24

  # Phone
  - name: "phone"
    type: "text"
    label: "Phone Number"
    page: 1
    required: true
    placeholder: "(555) 123-4567"
    position:
      x: 350
      y: 590
      width: 180
      height: 24

  # Address
  - name: "address"
    type: "textarea"
    label: "Current Address"
    page: 1
    maxLength: 200
    position:
      x: 72
      y: 470
      width: 460
      height: 80

  # Employment Type
  - name: "employment_type"
    type: "radio"
    label: "Desired Employment Type"
    page: 1
    required: true
    options:
      - value: "full_time"
        label: "Full-Time"
      - value: "part_time"
        label: "Part-Time"
      - value: "contract"
        label: "Contract"
      - value: "internship"
        label: "Internship"
    default: "full_time"
    position:
      x: 72
      y: 400

  # Remote Work Interest
  - name: "remote_work"
    type: "checkbox"
    label: "I am interested in remote work opportunities"
    page: 1
    position:
      x: 72
      y: 280

  # Start Date
  - name: "start_date"
    type: "text"
    label: "Available Start Date"
    page: 1
    required: true
    placeholder: "MM/DD/YYYY"
    position:
      x: 72
      y: 220
      width: 150
      height: 24

  # Salary Expectation
  - name: "salary_expectation"
    type: "dropdown"
    label: "Salary Expectation"
    page: 1
    options:
      - "$30,000 - $50,000"
      - "$50,000 - $75,000"
      - "$75,000 - $100,000"
      - "$100,000 - $150,000"
      - "$150,000+"
      - "Negotiable"
    position:
      x: 250
      y: 220
      width: 180
      height: 24

  # ===== PAGE 2: Experience & Certification =====

  # Years of Experience
  - name: "experience_years"
    type: "dropdown"
    label: "Years of Relevant Experience"
    page: 2
    required: true
    options:
      - "Less than 1 year"
      - "1-2 years"
      - "3-5 years"
      - "5-10 years"
      - "10+ years"
    position:
      x: 72
      y: 650
      width: 180
      height: 24

  # Education Level
  - name: "education"
    type: "dropdown"
    label: "Highest Education Level"
    page: 2
    required: true
    options:
      - "High School"
      - "Some College"
      - "Associate's Degree"
      - "Bachelor's Degree"
      - "Master's Degree"
      - "Doctorate"
    position:
      x: 280
      y: 650
      width: 180
      height: 24

  # Work History
  - name: "work_history"
    type: "textarea"
    label: "Work History (most recent positions)"
    page: 2
    required: true
    maxLength: 2000
    placeholder: "List your most recent positions, including company name, title, dates, and key responsibilities"
    position:
      x: 72
      y: 480
      width: 468
      height: 140

  # Skills
  - name: "skills"
    type: "textarea"
    label: "Key Skills & Qualifications"
    page: 2
    maxLength: 500
    placeholder: "List relevant skills, certifications, and qualifications"
    position:
      x: 72
      y: 320
      width: 468
      height: 100

  # How did you hear about us
  - name: "referral_source"
    type: "dropdown"
    label: "How did you hear about this position?"
    page: 2
    options:
      - "Company Website"
      - "LinkedIn"
      - "Indeed"
      - "Employee Referral"
      - "Job Fair"
      - "Other"
    position:
      x: 72
      y: 260
      width: 200
      height: 24

  # Legal Authorization
  - name: "work_authorization"
    type: "checkbox"
    label: "I am legally authorized to work in this country"
    page: 2
    required: true
    position:
      x: 72
      y: 200

  # Accurate Information Certification
  - name: "certify_accurate"
    type: "checkbox"
    label: "I certify that all information provided is accurate and complete"
    page: 2
    required: true
    position:
      x: 72
      y: 160

  # Signature
  - name: "applicant_signature"
    type: "signature"
    label: "Applicant Signature"
    page: 2
    required: true
    position:
      x: 72
      y: 80
      width: 250
      height: 50

# Note: Conditional fields and validation rules can be added here
# Example (requires corresponding field definitions):
# conditionalFields:
#   - trigger:
#       field: "employment_type"
#       value: "contract"
#     show: ["contract_duration"]
